---

- name: Ensure nginx is installed
  apt:
    name: nginx
    state: present

- name: Provide nginx config
  copy:
    src: default
    dest: /etc/nginx/sites-available/default

- name: Softlink nginx config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Ensure nginx is running
  systemd:
    name: nginx
    enabled: yes
    state: restarted
    daemon_reload: yes