---

- hosts: aws_ec2
  become: yes
  pre_tasks:
    - set_fact:
        vm_name: "{{ hostvars[inventory_hostname]['vm_name'] }}"
        cluster_ip: "{{ lookup('env', 'TF_VAR_CLUSTER_IP_START') }}"
        k8s_public_ip: "{{ lookup('env', 'KUBERNETES_PUBLIC_ADDRESS') }}"

    - name: Ensure system is updated
      apt:
        upgrade: yes
        update_cache: yes

    - name: Ensure tools are installed
      apt:
        name:
          - bat
          - net-tools
        state: present

- hosts: workers
  become: yes
  tasks:
    - name: Distribute certs/keys/kubeconfigs to workers
      copy:
        src: '{{ item }}'
        dest: '{{ ansible_env.HOME }}'
      loop:
        - pki/{{ vm_name }}-key.pem
        - pki/{{ vm_name }}.pem
        - pki/ca.pem
        - kubeconfigs/{{ vm_name }}.kubeconfig
        - kubeconfigs/kube-proxy.kubeconfig

- hosts: controllers
  become: yes
  tasks:
    - name: Distribute certs/keys/kubeconfigs to controllers
      copy:
        src: '{{ item }}'
        dest: '{{ ansible_env.HOME }}'
      loop:
        - pki/service-account-key.pem
        - pki/service-account.pem
        - pki/ca.pem
        - pki/ca-key.pem
        - pki/kubernetes-key.pem
        - pki/kubernetes.pem
        - kubeconfigs/admin.kubeconfig
        - kubeconfigs/kube-controller-manager.kubeconfig
        - kubeconfigs/kube-scheduler.kubeconfig
        - encryption-config.yml

    - import_role:
        name: etcd
    - import_role:
        name: control_plane