---
# Complete Ansible provisioning for https://github.com/prabhatsharma/kubernetes-the-hard-way-aws
- hosts: localhost
  connection: local
  tasks:

    - name: Add Charm repo
      become: yes
      yum_repository:
        name: Charm
        description: Charm Tool and Library
        baseurl: https://repo.charm.sh/yum/
        gpgkey: https://repo.charm.sh/yum/gpg.key

    - name: Install charms
      become: yes
      yum:
        name:
          - guma
        disable_gpg_check: yes
        state: present

    - name: Download awscli installer zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unarchive awscli installer zip
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Run installer script
      become: yes
      command: sh /tmp/aws/install
      args:
        creates: /usr/local/aws-cli

    - name: Set default Compute region for AWS
      command: aws configure set default.region {{ aws_region }}

    - name: Configure AWS credentials on controller
      shell: '{{ item }}'
      loop:
        - aws configure set default.aws_access_key_id $(skate get aws_access_key)
        - aws configure set default.aws_secret_access_key $(skate get aws_access_key_secret)
      no_log: true

    - name: Check AWS credentials
      command: aws sts get-caller-identity

    - name: Install PKI infra tools
      become: yes
      yum:
        name: golang-github-cloudflare-cfssl

    - name: Install kubectl
      become: yes
      get_url:
        url: https://dl.k8s.io/{{ kube_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/
        mode: 0755

    - name: Add Hashicorp repo
      become: yes
      yum_repository:
        baseurl: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        name: hashicorp
        description: hashicorp

    - name: Install Terraform
      become: yes
      yum:
        name: terraform
        state: present
