---

- name: Download etcd installer
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz

- name: Unpack etcd installer
  unarchive:
    src: /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install etcd binaries
  copy:
    src: /tmp/etcd-{{ etcd_version }}-linux-amd64/{{ item }}
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  loop:
    - etcd
    - etcdctl

- name: Ensure etcd config dir exists
  file:
    path: /etc/etcd
    state: directory

- name: Ensure etcd data dir exists
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0700

- name: Copy k8s keys to etcd
  copy:
    src: '{{ ansible_env.HOME}}/{{ item }}'
    dest: /etc/etcd/
    remote_src: yes
  loop:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

- name: Install etcd service file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Ensure etcd service is enabled/started
  systemd:
    name: etcd
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Verify etcd install
  command: >
    etcdctl member list
      --endpoints=https://127.0.0.1:2379
      --cacert=/etc/etcd/ca.pem
      --cert=/etc/etcd/kubernetes.pem
      --key=/etc/etcd/kubernetes-key.pem